upstream one_api {
    server 127.0.0.1:13000;
    keepalive 64;
}
server { #listening port
    server_name  api.xingshu.sh; 
    client_max_body_size 100m;
    gzip off;
    gzip_min_length 1k;
    gzip_buffers 4 16k;
    gzip_comp_level 2;
    gzip_types text/plain application/javascript application/x-javascript text/css application/xml text/javascript application/x-httpd-php image/jpeg image/gif image/png application/wasm;
    gzip_vary off;
    gzip_disable "MSIE [1-6]\.";

    default_type application/wasm;

    location ^~ /LLM/ {
        access_log off;
        log_not_found off;
        return 444;
    }

    location / {
        proxy_redirect off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;
        proxy_set_header Connection "";
        proxy_http_version 1.1;

        proxy_request_buffering off;
        proxy_buffering off;
        proxy_cache off;
        tcp_nodelay on;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
        send_timeout 3600s;
        proxy_pass http://one_api;
    }


}
